#include "s_command_catalog.h"

#include <algorithm>

namespace vectorPath
{

QStringList commandCompletionEntries()
{
    return {
        QStringLiteral("ARC"),
        QStringLiteral("ARC 3P"),
        QStringLiteral("ARC CSE"),
        QStringLiteral("ARC CSA 90"),
        QStringLiteral("ARC SCA 90"),
        QStringLiteral("ARC SCE"),
        QStringLiteral("ARC SEA 90"),
        QStringLiteral("ARC SED 45"),
        QStringLiteral("ARC SER 10"),
        QStringLiteral("ANGLEFORMAT DECIMAL"),
        QStringLiteral("ANGLEFORMAT DMS"),
        QStringLiteral("ANGLEFORMAT GRADS"),
        QStringLiteral("ANGLEFORMAT RADIANS"),
        QStringLiteral("ALIGN"),
        QStringLiteral("ARRAYPATH"),
        QStringLiteral("ARRAYPATH 6 ALIGN"),
        QStringLiteral("ARRAYPATH 6 NOALIGN"),
        QStringLiteral("ARRAYEDIT"),
        QStringLiteral("ARRAYEDIT PATH 6 ALIGN"),
        QStringLiteral("ARRAYEDIT POLAR 8 360"),
        QStringLiteral("ARRAYEDIT RECT 4 3 10 10"),
        QStringLiteral("ARRAYPOLAR"),
        QStringLiteral("ARRAYPOLAR 6 360"),
        QStringLiteral("ARRAYRECT"),
        QStringLiteral("ARRAYRECT 3 2"),
        QStringLiteral("AUTOSAVE"),
        QStringLiteral("AUDIT"),
        QStringLiteral("AUDIT CHECK"),
        QStringLiteral("BREAK"),
        QStringLiteral("BLEND"),
        QStringLiteral("CANCEL"),
        QStringLiteral("CHAMFER"),
        QStringLiteral("CHAMFER D 5 5"),
        QStringLiteral("CIRCLE"),
        QStringLiteral("CIRCLE 2P"),
        QStringLiteral("CIRCLE 3P"),
        QStringLiteral("CIRCLE DIAMETER"),
        QStringLiteral("CIRCLE TTR 5"),
        QStringLiteral("CIRCLE TTT"),
        QStringLiteral("CLOSE"),
        QStringLiteral("COMPLEMENT"),
        QStringLiteral("COPY"),
        QStringLiteral("CUI"),
        QStringLiteral("DIMLINEAR"),
        QStringLiteral("DIMALIGNED"),
        QStringLiteral("DIMANGULAR"),
        QStringLiteral("DIMRADIUS"),
        QStringLiteral("DIMDIAMETER"),
        QStringLiteral("DIMARC"),
        QStringLiteral("DIMORDINATE"),
        QStringLiteral("DIMSTYLE"),
        QStringLiteral("DIMSTYLE ADD ISO 2.5 2.5 1 3 2"),
        QStringLiteral("DIMSTYLE SET ISO"),
        QStringLiteral("DIMOVERRIDE STYLE ISO"),
        QStringLiteral("DIMOVERRIDE TEXT REF"),
        QStringLiteral("DIMOVERRIDE CLEAR"),
        QStringLiteral("DONE"),
        QStringLiteral("DXFOUT"),
        QStringLiteral("ERASE"),
        QStringLiteral("ELLIPSE"),
        QStringLiteral("DIAMOND"),
        QStringLiteral("EXPLODE"),
        QStringLiteral("EXTEND"),
        QStringLiteral("FILLET"),
        QStringLiteral("FILLET R 5"),
        QStringLiteral("GRID OFF"),
        QStringLiteral("GRID ON"),
        QStringLiteral("GRID SPACING 10"),
        QStringLiteral("GRID ROTATION 30"),
        QStringLiteral("GRIP_STRETCH"),
        QStringLiteral("GRIP_MOVE"),
        QStringLiteral("GRIP_ROTATE"),
        QStringLiteral("GRIP_SCALE"),
        QStringLiteral("GRIP_MIRROR"),
        QStringLiteral("HATCH"),
        QStringLiteral("HATCH SOLID"),
        QStringLiteral("HATCH PATTERN ANSI31 1 45"),
        QStringLiteral("HATCH PATTERN CROSS 2 0"),
        QStringLiteral("HATCH GRADIENT #488EFF #132D4D 0"),
        QStringLiteral("HATCHEDIT SOLID"),
        QStringLiteral("HATCHEDIT PATTERN ANSI32 1 45"),
        QStringLiteral("HEXAGON"),
        QStringLiteral("INTERSECT"),
        QStringLiteral("IMPORTSVG"),
        QStringLiteral("SVGIMPORT"),
        QStringLiteral("IMPORTBITMAP"),
        QStringLiteral("BITMAPIMPORT"),
        QStringLiteral("IMAGEIMPORT"),
        QStringLiteral("SVGFILL"),
        QStringLiteral("SVGDEDUP"),
        QStringLiteral("SVGDEDUP UPPER"),
        QStringLiteral("SVGDEDUP LOWER"),
        QStringLiteral("JOIN"),
        QStringLiteral("LAYER DELETE layer"),
        QStringLiteral("LAYER CLEAR layer"),
        QStringLiteral("LAYER DISPLAY layer ON"),
        QStringLiteral("LAYER DISPLAY layer OFF"),
        QStringLiteral("LAYER COLOR layer #37A6E6"),
        QStringLiteral("LAYER MERGECOLOR"),
        QStringLiteral("LENGTHEN"),
        QStringLiteral("LINE"),
        QStringLiteral("LUPREC 3"),
        QStringLiteral("KEYBOARD"),
        QStringLiteral("MIRROR"),
        QStringLiteral("MIRROR VERTICAL"),
        QStringLiteral("MIRROR HORIZONTAL"),
        QStringLiteral("MOVE"),
        QStringLiteral("MLEADER"),
        QStringLiteral("MLEADER Note"),
        QStringLiteral("MTEXT"),
        QStringLiteral("MTEXT Notes"),
        QStringLiteral("NEW"),
        QStringLiteral("OPEN"),
        QStringLiteral("ORTHO OFF"),
        QStringLiteral("ORTHO ON"),
        QStringLiteral("OSNAP OFF"),
        QStringLiteral("OSNAP ON"),
        QStringLiteral("OTRACK OFF"),
        QStringLiteral("OTRACK ON"),
        QStringLiteral("OCTAGON"),
        QStringLiteral("PENTAGON"),
        QStringLiteral("PLINE"),
        QStringLiteral("PEDIT"),
        QStringLiteral("PEDIT WIDTH 1"),
        QStringLiteral("PEDIT REVERSE"),
        QStringLiteral("RECTANG"),
        QStringLiteral("REDO"),
        QStringLiteral("RECOVER"),
        QStringLiteral("AUTOZOOM"),
        QStringLiteral("AZ"),
        QStringLiteral("ROTATE"),
        QStringLiteral("ROTATE CW90"),
        QStringLiteral("ROTATE CW180"),
        QStringLiteral("ROTATE CCW90"),
        QStringLiteral("ROTATE CCW180"),
        QStringLiteral("REVERSE"),
        QStringLiteral("RV"),
        QStringLiteral("DRAWCOLOR #37A6E6"),
        QStringLiteral("SELCOLOR #37A6E6"),
        QStringLiteral("SAVE"),
        QStringLiteral("SIMULATE"),
        QStringLiteral("SIMPAUSE"),
        QStringLiteral("SIMSTEP"),
        QStringLiteral("SIMSTOP"),
        QStringLiteral("SIMSPEED UP"),
        QStringLiteral("SIMSPEED DOWN"),
        QStringLiteral("SIMTRACE ON"),
        QStringLiteral("SIMTRACE OFF"),
        QStringLiteral("TOOLPATH"),
        QStringLiteral("TPSORT LEFT TOP"),
        QStringLiteral("TPSORT LEFT BOTTOM"),
        QStringLiteral("TPSORT RIGHT TOP"),
        QStringLiteral("TPSORT RIGHT BOTTOM"),
        QStringLiteral("TPSORT SHORTEST REVERSE"),
        QStringLiteral("TPSORT SHORTEST FIXED"),
        QStringLiteral("SCALE"),
        QStringLiteral("SNAP 10"),
        QStringLiteral("SNAP OFF"),
        QStringLiteral("SNAP ON"),
        QStringLiteral("SHORTCUTS"),
        QStringLiteral("SPLINE"),
        QStringLiteral("SPLINEDIT"),
        QStringLiteral("SPLINEDIT MOVE 2 0 0"),
        QStringLiteral("SPLINEDIT POLYLINE 64"),
        QStringLiteral("SPLINEDIT REVERSE"),
        QStringLiteral("STRETCH"),
        QStringLiteral("STAR"),
        QStringLiteral("STYLE"),
        QStringLiteral("STYLE ADD Notes Microsoft_YaHei_UI 0 1"),
        QStringLiteral("STYLE SET Notes"),
        QStringLiteral("TEXT"),
        QStringLiteral("TEXTALIGN LEFT"),
        QStringLiteral("TEXTALIGN CENTER"),
        QStringLiteral("TEXTALIGN RIGHT"),
        QStringLiteral("TRIANGLE"),
        QStringLiteral("THEME DARK"),
        QStringLiteral("THEME HIGH"),
        QStringLiteral("THEME LIGHT"),
        QStringLiteral("TRIM"),
        QStringLiteral("SUBTRACT"),
        QStringLiteral("UNDO"),
        QStringLiteral("UNION"),
        QStringLiteral("UNITS"),
        QStringLiteral("UNITS MM"),
        QStringLiteral("UNITS INCH"),
        QStringLiteral("WIDTH 1 1"),
        QStringLiteral("AUPREC 2"),
        QStringLiteral("XOR"),
        QStringLiteral("ZOOM EXTENTS"),
    };
}

QStringList commandCompletionsForPrefix(const QString& prefix)
{
    const QString normalized_prefix = prefix.trimmed();
    if (normalized_prefix.isEmpty())
    {
        return {};
    }

    QStringList matches;
    for (const QString& entry : commandCompletionEntries())
    {
        if (entry.startsWith(normalized_prefix, Qt::CaseInsensitive))
        {
            matches.push_back(entry);
        }
    }
    std::sort(matches.begin(), matches.end(),
              [](const QString& first, const QString& second)
              {
                  return first.compare(second, Qt::CaseInsensitive) < 0;
              });
    return matches;
}

} // namespace vectorPath
