#pragma once

#include <QColor>
#include <QIcon>
#include <QString>

namespace smartGraphics
{

enum class SIconType
{
    Application,
    NewFile,
    OpenFile,
    Save,
    SaveAs,
    ImportSvg,
    ImportBitmap,
    SvgFill,
    SvgDeduplicate,
    ExportDxf,
    ExportDwg,
    Recovery,
    Audit,
    DrawLine,
    DrawCircle,
    DrawPolyline,
    DrawEllipse,
    DrawSpline,
    SplineEdit,
    PolylineEdit,
    DrawArc,
    DrawRectangle,
    ShapeStar,
    ShapeTriangle,
    ShapePentagon,
    ShapeHexagon,
    ShapeOctagon,
    ShapeDiamond,
    Select,
    Move,
    Copy,
    Rotate,
    Scale,
    Mirror,
    Trim,
    Extend,
    Break,
    Join,
    Explode,
    Stretch,
    Lengthen,
    Grip,
    Fillet,
    Chamfer,
    Blend,
    Align,
    ArrayRect,
    ArrayPolar,
    ArrayPath,
    ArrayEdit,
    Offset,
    BooleanUnion,
    BooleanIntersection,
    BooleanDifference,
    BooleanXor,
    BooleanComplement,
    Undo,
    Redo,
    ZoomExtents,
    Pan,
    Dimension,
    DimensionAligned,
    DimensionAngular,
    DimensionRadius,
    DimensionDiameter,
    DimensionArcLength,
    DimensionOrdinate,
    DimensionStyle,
    Text,
    MText,
    Leader,
    TextStyle,
    Hatch,
    HatchPattern,
    HatchGradient,
    HatchEdit,
    ThemeDark,
    ThemeLight,
    ThemeHighContrast,
    Theme,
    Viewport,
    Layers,
    Properties,
    ExternalReference,
    ToolPalette,
    DesignCenter,
    SheetSet,
    CompatibilityReport,
    CommandLine,
    ModelSpace,
    LayoutSpace,
    PageSetup,
    PlotStyle,
    PlotPreview,
    Print,
    ExportPdf,
    Publish,
    Snap,
    Grid,
    Ortho,
    Tracking,
    Lineweight,
    Settings,
    UiScale,
    Simulation,
    Play,
    Pause,
    Step,
    SpeedUp,
    SpeedDown,
    Direction,
    Sort,
    QuickReverse,
    RotateClockwise90,
    RotateClockwise180,
    RotateCounterclockwise90,
    RotateCounterclockwise180,
    MirrorVertical,
    MirrorHorizontal,
    Help
};

class SIconProvider final
{
  public:
    static QIcon createIcon(SIconType icon_type, const QColor& foreground,
                            const QColor& accent = QColor());
    static QString iconName(SIconType icon_type);
};

} // namespace smartGraphics
