#include "s_icon_provider.h"

namespace vectorPath
{

QString SIconProvider::iconName(SIconType icon_type)
{
    switch (icon_type)
    {
    case SIconType::Application:
        return QStringLiteral("application");
    case SIconType::NewFile:
        return QStringLiteral("new_file");
    case SIconType::OpenFile:
        return QStringLiteral("open_file");
    case SIconType::Save:
        return QStringLiteral("save");
    case SIconType::SaveAs:
        return QStringLiteral("save_as");
    case SIconType::ImportSvg:
        return QStringLiteral("import_svg");
    case SIconType::ImportBitmap:
        return QStringLiteral("import_bitmap");
    case SIconType::SvgFill:
        return QStringLiteral("svg_fill");
    case SIconType::SvgDeduplicate:
        return QStringLiteral("svg_deduplicate");
    case SIconType::ExportDxf:
        return QStringLiteral("export_dxf");
    case SIconType::ExportDwg:
        return QStringLiteral("export_dwg");
    case SIconType::Recovery:
        return QStringLiteral("recovery");
    case SIconType::Audit:
        return QStringLiteral("audit");
    case SIconType::DrawLine:
        return QStringLiteral("draw_line");
    case SIconType::DrawCircle:
        return QStringLiteral("draw_circle");
    case SIconType::DrawPolyline:
        return QStringLiteral("draw_polyline");
    case SIconType::DrawEllipse:
        return QStringLiteral("draw_ellipse");
    case SIconType::DrawSpline:
        return QStringLiteral("draw_spline");
    case SIconType::SplineEdit:
        return QStringLiteral("spline_edit");
    case SIconType::PolylineEdit:
        return QStringLiteral("polyline_edit");
    case SIconType::DrawArc:
        return QStringLiteral("draw_arc");
    case SIconType::DrawRectangle:
        return QStringLiteral("draw_rectangle");
    case SIconType::ShapeStar:
        return QStringLiteral("shape_star");
    case SIconType::ShapeTriangle:
        return QStringLiteral("shape_triangle");
    case SIconType::ShapePentagon:
        return QStringLiteral("shape_pentagon");
    case SIconType::ShapeHexagon:
        return QStringLiteral("shape_hexagon");
    case SIconType::ShapeOctagon:
        return QStringLiteral("shape_octagon");
    case SIconType::ShapeDiamond:
        return QStringLiteral("shape_diamond");
    case SIconType::Select:
        return QStringLiteral("select");
    case SIconType::Move:
        return QStringLiteral("move");
    case SIconType::Copy:
        return QStringLiteral("copy");
    case SIconType::Rotate:
        return QStringLiteral("rotate");
    case SIconType::Scale:
        return QStringLiteral("scale");
    case SIconType::Mirror:
        return QStringLiteral("mirror");
    case SIconType::Trim:
        return QStringLiteral("trim");
    case SIconType::Extend:
        return QStringLiteral("extend");
    case SIconType::Break:
        return QStringLiteral("break");
    case SIconType::Join:
        return QStringLiteral("join");
    case SIconType::Explode:
        return QStringLiteral("explode");
    case SIconType::Stretch:
        return QStringLiteral("stretch");
    case SIconType::Lengthen:
        return QStringLiteral("lengthen");
    case SIconType::Grip:
        return QStringLiteral("grip");
    case SIconType::Fillet:
        return QStringLiteral("fillet");
    case SIconType::Chamfer:
        return QStringLiteral("chamfer");
    case SIconType::Blend:
        return QStringLiteral("blend");
    case SIconType::Align:
        return QStringLiteral("align");
    case SIconType::ArrayRect:
        return QStringLiteral("array_rect");
    case SIconType::ArrayPolar:
        return QStringLiteral("array_polar");
    case SIconType::ArrayPath:
        return QStringLiteral("array_path");
    case SIconType::ArrayEdit:
        return QStringLiteral("array_edit");
    case SIconType::Offset:
        return QStringLiteral("offset");
    case SIconType::BooleanUnion:
        return QStringLiteral("boolean_union");
    case SIconType::BooleanIntersection:
        return QStringLiteral("boolean_intersection");
    case SIconType::BooleanDifference:
        return QStringLiteral("boolean_difference");
    case SIconType::BooleanXor:
        return QStringLiteral("boolean_xor");
    case SIconType::BooleanComplement:
        return QStringLiteral("boolean_complement");
    case SIconType::Undo:
        return QStringLiteral("undo");
    case SIconType::Redo:
        return QStringLiteral("redo");
    case SIconType::ZoomExtents:
        return QStringLiteral("zoom_extents");
    case SIconType::Pan:
        return QStringLiteral("pan");
    case SIconType::Dimension:
        return QStringLiteral("dimension");
    case SIconType::DimensionAligned:
        return QStringLiteral("dimension_aligned");
    case SIconType::DimensionAngular:
        return QStringLiteral("dimension_angular");
    case SIconType::DimensionRadius:
        return QStringLiteral("dimension_radius");
    case SIconType::DimensionDiameter:
        return QStringLiteral("dimension_diameter");
    case SIconType::DimensionArcLength:
        return QStringLiteral("dimension_arc_length");
    case SIconType::DimensionOrdinate:
        return QStringLiteral("dimension_ordinate");
    case SIconType::DimensionStyle:
        return QStringLiteral("dimension_style");
    case SIconType::Text:
        return QStringLiteral("text");
    case SIconType::MText:
        return QStringLiteral("mtext");
    case SIconType::Leader:
        return QStringLiteral("leader");
    case SIconType::TextStyle:
        return QStringLiteral("text_style");
    case SIconType::Hatch:
        return QStringLiteral("hatch");
    case SIconType::HatchPattern:
        return QStringLiteral("hatch_pattern");
    case SIconType::HatchGradient:
        return QStringLiteral("hatch_gradient");
    case SIconType::HatchEdit:
        return QStringLiteral("hatch_edit");
    case SIconType::ThemeDark:
        return QStringLiteral("theme_dark");
    case SIconType::ThemeLight:
        return QStringLiteral("theme_light");
    case SIconType::ThemeHighContrast:
        return QStringLiteral("theme_high_contrast");
    case SIconType::Theme:
        return QStringLiteral("theme");
    case SIconType::Viewport:
        return QStringLiteral("viewport");
    case SIconType::Layers:
        return QStringLiteral("layers");
    case SIconType::Properties:
        return QStringLiteral("properties");
    case SIconType::ExternalReference:
        return QStringLiteral("external_reference");
    case SIconType::ToolPalette:
        return QStringLiteral("tool_palette");
    case SIconType::DesignCenter:
        return QStringLiteral("design_center");
    case SIconType::SheetSet:
        return QStringLiteral("sheet_set");
    case SIconType::CompatibilityReport:
        return QStringLiteral("compatibility_report");
    case SIconType::CommandLine:
        return QStringLiteral("command_line");
    case SIconType::ModelSpace:
        return QStringLiteral("model_space");
    case SIconType::LayoutSpace:
        return QStringLiteral("layout_space");
    case SIconType::PageSetup:
        return QStringLiteral("page_setup");
    case SIconType::PlotStyle:
        return QStringLiteral("plot_style");
    case SIconType::PlotPreview:
        return QStringLiteral("plot_preview");
    case SIconType::Print:
        return QStringLiteral("print");
    case SIconType::ExportPdf:
        return QStringLiteral("export_pdf");
    case SIconType::Publish:
        return QStringLiteral("publish");
    case SIconType::Snap:
        return QStringLiteral("snap");
    case SIconType::Grid:
        return QStringLiteral("grid");
    case SIconType::Ortho:
        return QStringLiteral("ortho");
    case SIconType::Tracking:
        return QStringLiteral("tracking");
    case SIconType::Lineweight:
        return QStringLiteral("lineweight");
    case SIconType::Settings:
        return QStringLiteral("settings");
    case SIconType::UiScale:
        return QStringLiteral("ui_scale");
    case SIconType::Simulation:
        return QStringLiteral("simulation");
    case SIconType::Play:
        return QStringLiteral("play");
    case SIconType::Pause:
        return QStringLiteral("pause");
    case SIconType::Step:
        return QStringLiteral("step");
    case SIconType::SpeedUp:
        return QStringLiteral("speed_up");
    case SIconType::SpeedDown:
        return QStringLiteral("speed_down");
    case SIconType::Direction:
        return QStringLiteral("direction");
    case SIconType::Sort:
        return QStringLiteral("sort");
    case SIconType::QuickReverse:
        return QStringLiteral("quick_reverse");
    case SIconType::RotateClockwise90:
        return QStringLiteral("rotate_clockwise_90");
    case SIconType::RotateClockwise180:
        return QStringLiteral("rotate_clockwise_180");
    case SIconType::RotateCounterclockwise90:
        return QStringLiteral("rotate_counterclockwise_90");
    case SIconType::RotateCounterclockwise180:
        return QStringLiteral("rotate_counterclockwise_180");
    case SIconType::MirrorVertical:
        return QStringLiteral("mirror_vertical");
    case SIconType::MirrorHorizontal:
        return QStringLiteral("mirror_horizontal");
    case SIconType::Help:
        return QStringLiteral("help");
    }
    return QStringLiteral("unknown");
}

} // namespace vectorPath
