#include "vp_icon_provider.h"

namespace Vp
{

QString VpIconProvider::iconName(VpIconType icon_type)
{
    switch (icon_type)
    {
    case VpIconType::Application:
        return QStringLiteral("application");
    case VpIconType::NewFile:
        return QStringLiteral("new_file");
    case VpIconType::OpenFile:
        return QStringLiteral("open_file");
    case VpIconType::Save:
        return QStringLiteral("save");
    case VpIconType::SaveAs:
        return QStringLiteral("save_as");
    case VpIconType::ImportSvg:
        return QStringLiteral("import_svg");
    case VpIconType::ImportBitmap:
        return QStringLiteral("import_bitmap");
    case VpIconType::SvgFill:
        return QStringLiteral("svg_fill");
    case VpIconType::SvgDeduplicate:
        return QStringLiteral("svg_deduplicate");
    case VpIconType::ExportDxf:
        return QStringLiteral("export_dxf");
    case VpIconType::ExportDwg:
        return QStringLiteral("export_dwg");
    case VpIconType::Recovery:
        return QStringLiteral("recovery");
    case VpIconType::Audit:
        return QStringLiteral("audit");
    case VpIconType::DrawLine:
        return QStringLiteral("draw_line");
    case VpIconType::DrawCircle:
        return QStringLiteral("draw_circle");
    case VpIconType::DrawPolyline:
        return QStringLiteral("draw_polyline");
    case VpIconType::DrawEllipse:
        return QStringLiteral("draw_ellipse");
    case VpIconType::DrawSpline:
        return QStringLiteral("draw_spline");
    case VpIconType::SplineEdit:
        return QStringLiteral("spline_edit");
    case VpIconType::PolylineEdit:
        return QStringLiteral("polyline_edit");
    case VpIconType::DrawArc:
        return QStringLiteral("draw_arc");
    case VpIconType::DrawRectangle:
        return QStringLiteral("draw_rectangle");
    case VpIconType::ShapeStar:
        return QStringLiteral("shape_star");
    case VpIconType::ShapeTriangle:
        return QStringLiteral("shape_triangle");
    case VpIconType::ShapePentagon:
        return QStringLiteral("shape_pentagon");
    case VpIconType::ShapeHexagon:
        return QStringLiteral("shape_hexagon");
    case VpIconType::ShapeOctagon:
        return QStringLiteral("shape_octagon");
    case VpIconType::ShapeDiamond:
        return QStringLiteral("shape_diamond");
    case VpIconType::Select:
        return QStringLiteral("select");
    case VpIconType::Move:
        return QStringLiteral("move");
    case VpIconType::Copy:
        return QStringLiteral("copy");
    case VpIconType::Rotate:
        return QStringLiteral("rotate");
    case VpIconType::Scale:
        return QStringLiteral("scale");
    case VpIconType::Mirror:
        return QStringLiteral("mirror");
    case VpIconType::Trim:
        return QStringLiteral("trim");
    case VpIconType::Extend:
        return QStringLiteral("extend");
    case VpIconType::Break:
        return QStringLiteral("break");
    case VpIconType::Join:
        return QStringLiteral("join");
    case VpIconType::Explode:
        return QStringLiteral("explode");
    case VpIconType::Stretch:
        return QStringLiteral("stretch");
    case VpIconType::Lengthen:
        return QStringLiteral("lengthen");
    case VpIconType::Grip:
        return QStringLiteral("grip");
    case VpIconType::Fillet:
        return QStringLiteral("fillet");
    case VpIconType::Chamfer:
        return QStringLiteral("chamfer");
    case VpIconType::Blend:
        return QStringLiteral("blend");
    case VpIconType::Align:
        return QStringLiteral("align");
    case VpIconType::ArrayRect:
        return QStringLiteral("array_rect");
    case VpIconType::ArrayPolar:
        return QStringLiteral("array_polar");
    case VpIconType::ArrayPath:
        return QStringLiteral("array_path");
    case VpIconType::ArrayEdit:
        return QStringLiteral("array_edit");
    case VpIconType::Offset:
        return QStringLiteral("offset");
    case VpIconType::BooleanUnion:
        return QStringLiteral("boolean_union");
    case VpIconType::BooleanIntersection:
        return QStringLiteral("boolean_intersection");
    case VpIconType::BooleanDifference:
        return QStringLiteral("boolean_difference");
    case VpIconType::BooleanXor:
        return QStringLiteral("boolean_xor");
    case VpIconType::BooleanComplement:
        return QStringLiteral("boolean_complement");
    case VpIconType::Undo:
        return QStringLiteral("undo");
    case VpIconType::Redo:
        return QStringLiteral("redo");
    case VpIconType::ZoomExtents:
        return QStringLiteral("zoom_extents");
    case VpIconType::Pan:
        return QStringLiteral("pan");
    case VpIconType::Dimension:
        return QStringLiteral("dimension");
    case VpIconType::DimensionAligned:
        return QStringLiteral("dimension_aligned");
    case VpIconType::DimensionAngular:
        return QStringLiteral("dimension_angular");
    case VpIconType::DimensionRadius:
        return QStringLiteral("dimension_radius");
    case VpIconType::DimensionDiameter:
        return QStringLiteral("dimension_diameter");
    case VpIconType::DimensionArcLength:
        return QStringLiteral("dimension_arc_length");
    case VpIconType::DimensionOrdinate:
        return QStringLiteral("dimension_ordinate");
    case VpIconType::DimensionStyle:
        return QStringLiteral("dimension_style");
    case VpIconType::Text:
        return QStringLiteral("text");
    case VpIconType::MText:
        return QStringLiteral("mtext");
    case VpIconType::Leader:
        return QStringLiteral("leader");
    case VpIconType::TextStyle:
        return QStringLiteral("text_style");
    case VpIconType::Hatch:
        return QStringLiteral("hatch");
    case VpIconType::HatchPattern:
        return QStringLiteral("hatch_pattern");
    case VpIconType::HatchGradient:
        return QStringLiteral("hatch_gradient");
    case VpIconType::HatchEdit:
        return QStringLiteral("hatch_edit");
    case VpIconType::ThemeDark:
        return QStringLiteral("theme_dark");
    case VpIconType::ThemeLight:
        return QStringLiteral("theme_light");
    case VpIconType::ThemeHighContrast:
        return QStringLiteral("theme_high_contrast");
    case VpIconType::Theme:
        return QStringLiteral("theme");
    case VpIconType::Viewport:
        return QStringLiteral("viewport");
    case VpIconType::Layers:
        return QStringLiteral("layers");
    case VpIconType::Properties:
        return QStringLiteral("properties");
    case VpIconType::ExternalReference:
        return QStringLiteral("external_reference");
    case VpIconType::ToolPalette:
        return QStringLiteral("tool_palette");
    case VpIconType::DesignCenter:
        return QStringLiteral("design_center");
    case VpIconType::SheetSet:
        return QStringLiteral("sheet_set");
    case VpIconType::CompatibilityReport:
        return QStringLiteral("compatibility_report");
    case VpIconType::CommandLine:
        return QStringLiteral("command_line");
    case VpIconType::ModelSpace:
        return QStringLiteral("model_space");
    case VpIconType::LayoutSpace:
        return QStringLiteral("layout_space");
    case VpIconType::PageSetup:
        return QStringLiteral("page_setup");
    case VpIconType::PlotStyle:
        return QStringLiteral("plot_style");
    case VpIconType::PlotPreview:
        return QStringLiteral("plot_preview");
    case VpIconType::Print:
        return QStringLiteral("print");
    case VpIconType::ExportPdf:
        return QStringLiteral("export_pdf");
    case VpIconType::Publish:
        return QStringLiteral("publish");
    case VpIconType::Snap:
        return QStringLiteral("snap");
    case VpIconType::Grid:
        return QStringLiteral("grid");
    case VpIconType::Ortho:
        return QStringLiteral("ortho");
    case VpIconType::Tracking:
        return QStringLiteral("tracking");
    case VpIconType::Lineweight:
        return QStringLiteral("lineweight");
    case VpIconType::Settings:
        return QStringLiteral("settings");
    case VpIconType::UiScale:
        return QStringLiteral("ui_scale");
    case VpIconType::Simulation:
        return QStringLiteral("simulation");
    case VpIconType::Play:
        return QStringLiteral("play");
    case VpIconType::Pause:
        return QStringLiteral("pause");
    case VpIconType::Step:
        return QStringLiteral("step");
    case VpIconType::SpeedUp:
        return QStringLiteral("speed_up");
    case VpIconType::SpeedDown:
        return QStringLiteral("speed_down");
    case VpIconType::Direction:
        return QStringLiteral("direction");
    case VpIconType::Sort:
        return QStringLiteral("sort");
    case VpIconType::QuickReverse:
        return QStringLiteral("quick_reverse");
    case VpIconType::RotateClockwise90:
        return QStringLiteral("rotate_clockwise_90");
    case VpIconType::RotateClockwise180:
        return QStringLiteral("rotate_clockwise_180");
    case VpIconType::RotateCounterclockwise90:
        return QStringLiteral("rotate_counterclockwise_90");
    case VpIconType::RotateCounterclockwise180:
        return QStringLiteral("rotate_counterclockwise_180");
    case VpIconType::MirrorVertical:
        return QStringLiteral("mirror_vertical");
    case VpIconType::MirrorHorizontal:
        return QStringLiteral("mirror_horizontal");
    case VpIconType::Help:
        return QStringLiteral("help");
    }
    return QStringLiteral("unknown");
}

} // namespace Vp
