name: Windows build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  core:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        config: [Debug, Release]
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262
        with:
          persist-credentials: false
      - name: Build and test without Qt
        shell: pwsh
        run: python sgraphBuildTools/vp_build_core.py --config ${{ matrix.config }} --jobs 4

  build:
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        include:
          - bits: "64"
            config: release
            qt_arch: win64_msvc2017_64
          - bits: "32"
            config: release
            qt_arch: win32_msvc2017

    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Install Qt 5.12.10
        uses: jurplel/install-qt-action@48d3ad6db93f3627c8ee7a0454bc6f3744f7e730 # v4.3.1
        with:
          version: "5.12.10"
          arch: ${{ matrix.qt_arch }}
          cache: true

      - name: Build and test
        shell: pwsh
        run: |
          $qtDir = (& qmake -query QT_INSTALL_PREFIX).Trim()
          python "sgraphBuildTools/vp_build_${{ matrix.bits }}_${{ matrix.config }}.py" `
            --qt-dir $qtDir --clean --jobs 4
